### ISSUE TITLE
Theme status

### ISSUE THREAD

**Issue by geotheory** [brandoncardoso/hima#1]
Hi Brandon. This looks like a very nice project. What stage of development do you consider it at? I can't see any version numbering.

Do you have any plans for security validation?

**Comment by brandoncardoso** [comment]
Hey Robin. There is a version number in the hima.gemspec file, but I will add tags on Github. It's currently at v1.0.5, I'd say it has a complete design and basic features for a personal site/blog. Open to any suggestions, comments or pull requests!

**Comment by geotheory** [comment]
Thanks for confirming, Brandon.

One quick question - how would you recommend user overrides the background colour (css variable `$white0h` in `./_sass/hima/colourschemes/_gruvbox-colours.scss`)?  Can it be done from `_config.yml` or is there another way that keeps leaves `_sass/*` untouched?

I've also tried adding `$white0h:          #ff0000 !important;` to `_sass/hima/custom-variables.scss` but no effect.

**Comment by brandoncardoso** [comment]
Try `$background: #ff0000;` in `_sass/hima/custom-variables.scss` instead. If that doesn't work, then there might be bug. I'll confirm/fix when I can get to a computer (on a short vacation at the moment 😅)

Edit: `_sass` not `_assets`

**Comment by geotheory** [comment]
That fixed it thanks 👍

**Comment by brandoncardoso** [comment]
@geotheory I've added tags for the existing versions
